# Repository

- name: hhvm | add the repository
  copy: >
    content="deb http://dl.hhvm.com/ubuntu {{ ansible_lsb.codename }} main" 
    dest=/etc/apt/sources.list.d/hhvm.list
  sudo: yes
  when: ansible_os_family == 'Debian'

# Package

- name: hhvm | install debian hhvm nightly
  apt: >
    pkg={{ item }} 
    state=installed
    update_cache=true
  with_items: pkgs_hhvm_nightly
  sudo: yes
  when: ansible_os_family == 'Debian' and hhvm.nightly is defined and hhvm.nightly == 1

- name: hhvm | install debian hhvm
  apt: >
    pkg={{ item }} 
    state=installed
    update_cache=true
  with_items: pkgs_hhvm
  sudo: yes
  when: ansible_os_family == 'Debian' and (hhvm.nightly is not defined or hhvm.nightly == 0)

- name: hhvm | install rpm hhvm
  yum: >
    pkg={{ item }} 
    state=installed
  with_items: pkgs_hhvm
  sudo: yes
  when: ansible_os_family in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat']

