- name: git | install dependencies
  apt: >
    pkg={{ item }} 
    state=latest
  with_items:
    - git-core
  sudo: yes

- name: git | check for source repo
  fail: msg="Repository - {{ item.name }} - Source is missing"
  with_items: applications.repository
  when: item.install == 1 and item.options.provider is defined and item.options.provider == 'git' and item.options.source is not defined

- name: git | verify install paths
  file: >
    path={{ item.path }}
    state=directory
  with_items: applications.repository
  when: item.install == 1 and item.options.provider is defined and item.options.provider == 'git'

- name: git | debug pre-installation
  debug: >
    msg="{{ item.options.pre_install|join(' && ') }}"
  with_items: applications.repository
  when: item.install == 1 and item.options.provider is defined and item.options.provider == 'git' and item.options.pre_install is defined and item.options.pre_install

#- name: git | pre-installation commands
#  command: >
#    {{ item.options.pre_install|join(' && ') }}
#    chdir={{ item.path }}
#  with_items: applications.repository
#  when: item.install == 1 and item.options.provider is defined and item.options.provider == 'git' and item.options.pre_install is defined and item.options.pre_install

- name: git | install git application
  git: >
    repo={{ item.options.source }}
    dest={{ item.path }}
    version={{ item.options.revision|default('master') }}
  with_items: applications.repository
  when: item.install == 1 and item.options.provider is defined and item.options.provider == 'git'

- name: git | debug post-installation
  debug: >
    msg="{{ item.options.post_install|join(' && ') }}"
  with_items: applications.repository
  when: item.install == 1 and item.options.provider is defined and item.options.provider == 'git' and item.options.post_install is defined and item.options.post_install

#- name: git | post-installation commands
#  command: >
#    {{ item.options.post_install|join(' && ') }}
#    chdir={{ item.path }}
#  with_items: applications.repository
#  when: item.install == 1 and item.options.provider is defined and item.options.provider == 'git' and item.options.post_install is defined and item.options.post_install
