- name: protobox | add apache configurations
  template: >
    src=protobox.conf.j2
    dest=/etc/apache2/sites-available/00-protobox.conf
    mode=0640
  with_items: apache.vhosts
  sudo: yes
  notify:
    - apache-restart

- name: protobox | activates our virtualhost
  command: a2ensite protobox.conf
  sudo: yes
