# Gems

- name: ruby | install debian gem dependencies
  apt: >
    name={{ item }}
    state=latest
  with_items: pkgs_ruby_gems
  sudo: yes
  when: ruby.gems is defined

- name: ruby | install rpm gem dependencies
  yum: >
    pkg={{ item }}
    state=installed
  with_items: pkgs_ruby_gems
  sudo: yes
  when: ansible_os_family in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat'] and ruby.gems is defined

- name: ruby | install gems
  command: >
    gem install {{ item }} --no-ri --no-rdoc
  with_items: ruby.gems
  sudo: yes
  when: ruby.gems is defined

