# Package - Debian

- name: app | add key
  apt_key: >
    url={{ apt_key_rabbitmq }}
    state=present
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: app | add the repository
  copy: >
    content="deb http://www.rabbitmq.com/debian/ {{ rabbitmq.release|default('stable') }} main" 
    dest=/etc/apt/sources.list.d/rabbitmq.list
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: app | install debian rabbitmq
  apt: >
    pkg={{ item }} 
    state=latest
    update_cache=true
  with_items: pkgs_rabbitmq
  sudo: yes
  when: ansible_os_family == 'Debian'

# Package - RedHat

- name: app | add key
  rpm_key: > 
    key={{ apt_key_rabbitmq }}
    state=present
  sudo: yes
  when: ansible_os_family in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat']

- name: app | install rpm rabbitmq
  yum: >
    pkg={{ item }} 
    state=latest
    update_cache=true
  with_items: pkgs_rabbitmq
  sudo: yes
  when: ansible_os_family in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat']
